### ISSUE TITLE
Optional compress for mediabackup

### ISSUE THREAD

**Issue by abriel** [mjs7231/django-dbbackup#43]
Hi folks,
I think you know that MEDIA_PATH usually contains non-plain files like images and may be videos.
And probably we want only tar them, because do another compress on them by gzip is useless.
Could it be a --compress option like for dbbackup? 
Thanks.

**Comment by benjaoming** [comment]
That sounds like a great idea! :+1: 

But I think if you introduce the `--compress` option as it is, then you'll break existing behaviour, i.e. people who upgrade will start having their files called .tar instead of .tar.gz

Maybe this can be fixed by creating both a `--no-compress` and `--compress`, and having none of them defaults to tar.gz ?

**Comment by abriel** [comment]
I agree with `--no-compress` also. But from another side, dbbackup has no compress by default, but mediabackup will have compress by default. 
But generally you are right. New features should not break expected behavior comes from previous versions.
Thanks.

**Comment by benjaoming** [comment]
@abriel IMO `tar` is a less used container format in its unwrapped form, and it's more "conventional" to use tar.gz (or tar.bz)... but your point that it's (most likely) just a waste of CPU cycles for the media folder remains!
